### ISSUE TITLE
一些TW字形可能需要改變 (比如: 最, 即, 明, 朝, 的, etc.)

### ISSUE THREAD

**Issue by Marcus98T** [ButTaiwan/genryu-font#1]
我還以為有些字形還沒有改變，所以提出來。右邊的隱藏字形都在思源黑體/明體字體裡面。

![glyph change](https://user-images.githubusercontent.com/10541683/46363608-1391e780-c6a6-11e8-8c27-fdf379b97706.png)
![default](https://user-images.githubusercontent.com/10541683/46365883-48a13880-c6ac-11e8-9238-14fd60e5b4c1.png)

請參考此鏈接: [https://github.com/MoneMizuno/Genne-Gothic](https://github.com/MoneMizuno/Genne-Gothic)和[這個文件](https://github.com/MoneMizuno/Genne-Gothic/blob/master/Other/Other/CMap%E6%9B%BF%E6%8F%9B%E8%A1%A8_Genne%20Gothic_1.004.ods)。

這些建議包括你所有的字形。原諒我重複issues。多謝。

**Comment by ButTaiwan** [comment]
1. 此次部首統一作業僅限於Big5範圍內（即用一般用注音輸入法容易輸入的字部件不統一者。）故戸、経之類都不在處理範圍。（這次調整字形，是為了解決一般繁體中文文件常用字如青、請部件不統一的問題。而這些非Big5文字，可解讀為使用者故意輸入的，沒必要統一部件。）

2. 部分部件（如月），雖然部份文字確實右側不接觸版本可選。但更多文字沒得選，選了反而造成不統一，多數選擇不改。

3. 橫點，原則上除了少部分文字外都不選。如上所說，只有部份文字能選，選了反而造成部件不統一。

4. 最、冒…類，猶豫到後來的結果是選曰。傳統鉛字（一般印刷品）最常見的寫法是曰。

5. 部份文字是實用性考量（如再、冉兩字不出頭。勺、的、約、釣四字從點。）

**Comment by ButTaiwan** [comment]
整併至此
https://github.com/ButTaiwan/genyo-font/issues/9
