### ISSUE TITLE
何時variable-font化？

### ISSUE THREAD

**Issue by cang-mang** [ButTaiwan/genryu-font#10]
思源宋體都已經基於可變字體（variable font）技術來做了，源流明體能這麽做嗎？

**Comment by ButTaiwan** [comment]
此專案當時使用的工具目前似乎還沒完全支援可變字體，考慮到程式碼移轉成本龐大，主要使用需求也不大，除了可變字型之外，還是需要另外匯出既有固定字型的版本，維護成本過高。
短期內應該是不會有任何製作為可變字型的計畫。
