### ISSUE TITLE
有没有可能製作出一種特殊的字體

### ISSUE THREAD

**Issue by ChihSee-Hsie** [ButTaiwan/genryu-font#12]
在古典排版的書籍中，常會見到雙行夾註。夾註中的字體其寬度爲正文的二分之一，而高度略小於正文、字距因而略大於正文，整體呈現出瘦高的取勢。其例子如下：

[書格提供　王弼註《周易》書影](https://new.shuge.org/wp-content/uploads/2023/02/zhou_yi_wang_zhu02-1000x977.jpg)

相應的電腦字型，其字高應當與平常一致，但上下有一點留白；字寬則爲平常的一半。我曾經使用 FontForge 試圖製作符合這種標準的字型，但效果不堪入目，因此向　貴團隊求助。此致，順祝　祺安！

**Comment by ButTaiwan** [comment]
無暇製作。
