### ISSUE TITLE
詢問關於將原字型轉換為復古字型之程式

### ISSUE THREAD

**Issue by Vanadianfan** [ButTaiwan/genryu-font#13]
觀察到此字型對「復古」的處理，是統一在原字型部分筆畫上加入或修改若干細節，即使得整體文字風格美觀程度大大提升。
想請問作者方面是否有意願開源該程式碼？也可吸引更多人共同改進演算法，使其對筆畫的識別力再增強。

**Comment by ButTaiwan** [comment]
目前沒有公開打算。
