### ISSUE TITLE
一部欧文グリフがフォント内に存在しない

### ISSUE THREAD

**Issue by h-mikisato** [ButTaiwan/genryu-font#3]
Source Han Serifには存在する一部欧文グリフが、源流明朝フォント内には存在しないようです。
以下はMicrosoft Wordによる確認です。「ć」のみ該当のグリフがなく、フォントが置き換わっています。

![glyph](https://user-images.githubusercontent.com/15855742/54772718-5000d200-4c4b-11e9-99b7-23cbfbfd6906.PNG)

LuaLaTeXを利用してのフォント埋め込みを行った場合にも、「ć」が欠けているのを確認しました。
確認した範囲では「ć」のみですが、もしかしたら他にもあるかもしれません。

**Comment by ButTaiwan** [comment]
現在 JP フォントの文字セットは、おおむね Adobe-Japan1-6 にしていますので、
恐らく Adobe-Japan1-6 には「ć」が存在しないからです。

Source Han Serif に存在する欧文文字は「ć」のほかにも例えば大量にあるベトナム文字があります。（「ở」など）
簡体字とハングルだけ削除して、欧文を全て保留するようなポリシーで作るなら、文字数がかなり増えることが予想されます。

**Comment by h-mikisato** [comment]
ご説明ありがとうございます。お手数おかけいたしました。
