### ISSUE TITLE
請問有 CJK 版本嗎?

### ISSUE THREAD

**Issue by bluelovers** [ButTaiwan/genryu-font#4]
請問有 CJK 版本嗎? 因為希望能顯示所有漢字

**Comment by ButTaiwan** [comment]
TW版本應該就是有保留所有漢字了（只是只保留一種寫法）。

**Comment by bluelovers** [comment]
我將檔案放進 gource 裡面 取代 字體後 發現會有部分字 仍然無法顯示

**Comment by ButTaiwan** [comment]
是哪些字缺？
如果 TW 版本都沒支援的話，應該是思源本來就缺的字？
