### ISSUE TITLE
部首『酉』的『儿』框里框外粗细不合

### ISSUE THREAD

**Issue by cang-mang** [ButTaiwan/genryu-font#6]
比如『配』這個字，粗體更明顯。源流、源雲、源石、源泉都有這個問題。源樣没有用過，不知道。

**Comment by ButTaiwan** [comment]
這是思源黑體的原始設計。

而且幾乎所有粗體的字型，都是這樣設計的。為了視覺平衡。

如果將框內做得跟框外一樣粗，那框內就一團全塗黑了。如果將框外做得跟框內一樣細，那個部份會明顯細得非常礙眼，愈粗的字重愈明顯、愈礙眼。

所以這種視覺修正是必要的。

當然，當盯著這個字仔細看時，會發現筆劃粗細不連續。
但字體本來就不是用來仔細看一筆一劃的，而是追求整體閱讀時看起來最均勻的。



如果真的很在意這個問題，也許只能考慮都用細體。

**Comment by cang-mang** [comment]
嗯，小字號看著還行。大字號就有點碍眼了……
<img width="225" alt="not_fit" src="https://user-images.githubusercontent.com/61035897/95648339-e84df880-0b08-11eb-8ff2-f8b72ce40c19.png">
